name: mplay_mobile
description: A new Flutter project for mPlay.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  provider: ^6.0.5
  google_fonts: ^6.1.0
  file_picker: ^6.1.1
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  audio_session: ^0.1.18
  flutter_animate: ^4.2.0
  glassmorphism: ^3.0.0
  percent_indicator: ^4.2.3
  video_player: 2.8.6
  chewie: 1.7.0
  dio: ^5.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
